name = "pangea_api"
language = "rust"
type = "actor"
version = "0.1.2"

[actor]
claims = [
    "wasmcloud:httpclient",
    "wasmcloud:builtin:logging",
    "wasmcloud:keyvalue"
]
call_alias = "iiot/pangea_api"